name: Generate Changelog
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md' # Prevents the action from triggering itself

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to allow the action to push the new changelog
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: "CHANGELOG.md"
          skip-version-file: "true" # Keep this true if you don't have a package.json